### ISSUE TITLE
BusinessObject: Exception when XML document is incomplete

### ISSUE THREAD

**Issue by wapcaplet** [a-e/cherby#1]
When a BusinessObject is missing expected XML elements, weird unhandled exceptions like this one can crop up later:

```
undefined method `add_child' for nil:NilClass
/home/eric/.rvm/gems/ruby-1.9.3-p194@jira-to-cherwell/gems/cherby-0.0.2/lib/cherby/business_object.rb:54:in `get_field_node'
/home/eric/.rvm/gems/ruby-1.9.3-p194@jira-to-cherwell/gems/cherby-0.0.2/lib/cherby/business_object.rb:131:in `[]'
/home/eric/.rvm/gems/ruby-1.9.3-p194@jira-to-cherwell/gems/cherby-0.0.2/lib/cherby/incident.rb:21:in `id'
/home/eric/.rvm/gems/ruby-1.9.3-p194@jira-to-cherwell/gems/cherby-0.0.2/lib/cherby/incident.rb:27:in `exists?'
```

Possible solution: Build XML skeleton at initialization, or on the fly.

**Comment by wapcaplet** [comment]
Fixed by checking expected DOM format when BusinessObjects are initialized, and when traversing the DOM, and raising a `Cherby::BadFormat` exception when the DOM doesn't have the expected structure. Closing.
